jobs:
  workflow:
    name: Ci
    runs-on: ubuntu-20.04

    steps:
      - name: Startup
        uses: actions/checkout@v2
      - name: Get Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./ci/main

name: Run

on:
  schedule:
    - cron: "45 */6 * * *"
